/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import genetic.nsga.VRPNSGAIIIRunner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        if (args.length > 0 && args[0].equals("test-nsga3")) {
            System.out.println("=== Executando Teste do NSGA-III com Novos Operadores ===\n");
            VRPNSGAIIIRunner.main(new String[0]);
        } else {
            System.out.println(new App().getGreeting());
            System.out.println("Use: gradle run --args='test-nsga3' para testar NSGA-III");
        }
    }
}
