/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // JMetal dependencies
    implementation("org.uma.jmetal:jmetal-core:6.0")
    implementation("org.uma.jmetal:jmetal-algorithm:6.0")
    implementation("org.uma.jmetal:jmetal-problem:6.0")
    
    // Apache Commons IO (necessário para JMetal)
    implementation("commons-io:commons-io:2.11.0")
    
    testImplementation("org.junit.jupiter:junit-jupiter")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

application {
    // Define the main class for the application.
    mainClass = "main.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}

// Task to run JMetal test
tasks.register<JavaExec>("runJMetalTest") {
    group = "application"
    description = "Run JMetal test"
    classpath = sourceSets.main.get().runtimeClasspath
    mainClass.set("jmetaltest.JMetalTest")
}

// Task to run VRPSolution test
tasks.register<JavaExec>("runVRPSolutionTest") {
    group = "application"
    description = "Run VRPSolution test"
    classpath = sourceSets.main.get().runtimeClasspath
    mainClass.set("genetic.nsga.VRPSolutionTest")
}

// Task to run NSGA-III with new genetic operators
tasks.register<JavaExec>("runNSGA3Test") {
    group = "application"
    description = "Run NSGA-III with new genetic operators"
    classpath = sourceSets.main.get().runtimeClasspath
    mainClass.set("genetic.nsga.VRPNSGAIIIRunner")
}
